ForkUpgradeBatchNumber = 0
ForkUpgradeNewForkId = 0

[Log]
Environment = "development"
Level = "info"
Outputs = ["stderr"]

[NetworkConfig.L1]
L1ChainID = 1
PolAddr = "0x5FbDB2315678afecb367f032d93F642f64180aa3"
ZkEVMAddr = "0xeb173087729c88a47568AF87b17C653039377BA6"
RollupManagerAddr = "0x2d42E2899662EFf08b13eeb65b154b904C7a1c8a"
GlobalExitRootManagerAddr = "0xB8cedD4B9eF683f0887C44a6E4312dC7A6e2fcdB"

[Etherman]
	URL="https://rpc.ankr.com/eth/xxxxx"
	ForkIDChunkSize=100
	[Etherman.EthermanConfig]
		URL="https://rpc.ankr.com/eth/xxxxx"
		MultiGasProvider=false
		L1ChainID=1

[Common]
NetworkID = 1
IsValidiumMode = true
ContractVersions = "banana"

[Aggregator]
Host = "0.0.0.0"
Port = 50081
RetryTime = "5s"
VerifyProofInterval = "10s"
ProofStatePollingInterval = "5s"
TxProfitabilityCheckerType = "acceptall"
TxProfitabilityMinReward = "1.1"
IntervalAfterWhichBatchConsolidateAnyway="0s"
BatchProofSanityCheckEnabled = true
ChainID = 0
ForkId = 13
SenderAddress = "0x70997970c51812dc3a010c7d01b50e0d17dc79c8"
CleanupLockedProofsInterval = "2m"
GeneratingProofCleanupThreshold = "10m"
GasOffset = 0
RPCURL = "https://rpc.xlayer.tech/unlimited/yyy"
WitnessURL = "https://rpc.xlayer.tech/unlimited/yyy"
UseFullWitness = false
SettlementBackend = "l1"
AggLayerTxTimeout = "5m"
AggLayerURL = ""
SyncModeOnlyEnabled = false
	[Aggregator.SequencerPrivateKey]
		Path = "/pk/sequencer.keystore"
		Password = "testonly"
	[Aggregator.DB]
		Name = "aggregator_db"
		User = "aggregator_user"
		Password = "aggregator_password"
		Host = "xlayer-fep-agg-db"
		Port = "5432"
		EnableLog = false	
		MaxConns = 200
	[Aggregator.Log]
		Environment = "development"
		Level = "info"
		Outputs = ["stderr"]
	[Aggregator.EthTxManager]
		FrequencyToMonitorTxs = "1s"
		WaitTxToBeMined = "2m"
		GetReceiptMaxTime = "250ms"
		GetReceiptWaitInterval = "1s"
		PrivateKeys = [
			{Path = "/pk/aggregator.keystore", Password = "testonly"},
		]
		ForcedGas = 0
		GasPriceMarginFactor = 1
		MaxGasPriceLimit = 0
		StoragePath = "/tmp/cdk/ethtxmanager.sqlite"
		ReadPendingL1Txs = false
		SafeStatusL1NumberOfBlocks = 0
		FinalizedStatusL1NumberOfBlocks = 0
			[Aggregator.EthTxManager.Etherman]
				URL = "https://rpc.ankr.com/eth/xxxxx"
				L1ChainID = 1
				HTTPHeaders = []
	[Aggregator.Synchronizer]
		[Aggregator.Synchronizer.Log]
			Environment = "development"
			Level = "info"
			Outputs = ["stderr"]
		[Aggregator.Synchronizer.SQLDB]
			DriverName = "sqlite3"
			DataSource = "/tmp/cdk/aggregator_sync_db.sqlite"
		[Aggregator.Synchronizer.Synchronizer]
			SyncInterval = "10s"
			SyncChunkSize = 1000
			GenesisBlockNumber = 353
			SyncUpToBlock = "finalized"
			BlockFinality = "finalized"
			OverrideStorageCheck = false
		[Aggregator.Synchronizer.Etherman]
			L1URL = "https://rpc.ankr.com/eth/xxxxx"
			ForkIDChunkSize = 100
			L1ChainID = 1
			PararellBlockRequest = false
			[Aggregator.Synchronizer.Etherman.Contracts]
				GlobalExitRootManagerAddr = "0xB8cedD4B9eF683f0887C44a6E4312dC7A6e2fcdB"
				RollupManagerAddr = "0x2d42E2899662EFf08b13eeb65b154b904C7a1c8a"
				ZkEVMAddr = "0xeb173087729c88a47568AF87b17C653039377BA6"
			[Aggregator.Synchronizer.Etherman.Validium]
				Enabled = true
				TrustedSequencerURL = ""
				RetryOnDACErrorInterval = "1m"
				DataSourcePriority = ["trusted", "external"]
			[Aggregator.Synchronizer.Etherman.Validium.Translator]
				FullMatchRules = []
			[Aggregator.Synchronizer.Etherman.Validium.RateLimit]
				NumRequests = 1000
				Interval = "1s"
[ReorgDetectorL1]
DBPath = "/tmp/cdk/reorg_detector_l1.sqlite"

[L1InfoTreeSync]
DBPath = "/tmp/cdk/l1_info_tree_sync.sqlite"
GlobalExitRootAddr="0xB8cedD4B9eF683f0887C44a6E4312dC7A6e2fcdB"
RollupManagerAddr = "0x2d42E2899662EFf08b13eeb65b154b904C7a1c8a"
SyncBlockChunkSize=10
BlockFinality="LatestBlock"
WaitForNewBlocksPeriod="100ms"
InitialBlock= 353
