[Log]
Environment = "production"
Level = "debug"

[NetworkConfig.L1]
URL = "http://anvil:8545"
ChainID = 1
ZkEVMAddr = "0x2B0ee28D4D51bC9aDde5E58E295873F61F4a0507"
RollupManagerAddr = "0x5132a183e9f3cb7c848b0aac5ae0c4f0491b7ab2"
POLTokenAddr = "0x455e53CBB86018Ac2B8092FdCd39d8444aFFC3F6"
GlobalExitRootManagerAddr = "0x580bda1e7A0CFAe92Fa7F6c20A3794F169CE3CFb"

[Etherman]
URL = "http://anvil:8545"
ForkIDChunkSize = 0
[Etherman.EthermanConfig]
URL = "http://anvil:8545"
MultiGasProvider = false
L1ChainID = 1

[Common]
NetworkID = 3
ContractVersions = "banana"
IsValidiumMode = true
[Common.L2RPC]
URL = "https://xlayerrpc.okx.com/unlimited/abc"
Mode = "basic"

[AggSender]
KeepCertificatesHistory = true
MaxCertSize = 0
MaxL2BlockNumber = 17425494
StopOnFinishedSendingAllCertificates = true
DryRun = false

AggsenderPrivateKey = {Path = "/etc/aggkit/sequencer.keystore", Password = "randompassword"}

AggLayerURL = "agglayer-node:4443" 
UseAgglayerTLS = false
StoragePath = "/tmp/aggsender.sqlite"
BlockFinality = "FinalizedBlock"
EpochNotificationPercentage = 0
MaxRetriesStoreCertificate = 0 # 0 means infinitie
EnableRPC = false
Mode = "PessimisticProof"
CheckStatusCertificateInterval = "1s"
MaxSubmitCertificateRate = { NumRequests = 20, Interval = "10m" }
GlobalExitRootL2Addr = "0xa40d5f56745a118d0906a34e69aec8c0db1cb8fa"
RequireNoFEPBlockGap = false

[ReorgDetectorL1] # needed by L1InfoTreeSync
DBPath = "/tmp/reorgdetectorl1.sqlite" 
CheckReorgsInterval = "30s"
FinalizedBlock = "FinalizedBlock"

[ReorgDetectorL2] # needed by BridgeL2Sync
DBPath = "/tmp/reorgdetectorl2.sqlite"
CheckReorgsInterval = "30s"
FinalizedBlock = "FinalizedBlock"

[L1InfoTreeSync]
DBPath = "/tmp/L1InfoTreeSync.sqlite"
GlobalExitRootAddr = "0x580bda1e7A0CFAe92Fa7F6c20A3794F169CE3CFb"
RollupManagerAddr = "0x5132a183e9f3cb7c848b0aac5ae0c4f0491b7ab2"
BlockFinality = "FinalizedBlock"
URLRPCL1 = "http://anvil:8545"
InitialBlock = 16896721

[BridgeL2Sync]
DBPath = "/tmp/BridgeL2Sync.sqlite" 
BlockFinality = "FinalizedBlock"
InitialBlockNum = 0
BridgeAddr = "0x2a3DD3EB832aF982ec71669E178424b10Dca2EDe"
SyncBlockChunkSize = 1000

[SqliteAPI]
Enabled = true
Host = "0.0.0.0"
Port = 7001
MaxRequestsPerIPAndSecond = 10