FROM docker.io/library/golang:1.24-alpine3.21 AS base

RUN apk --no-cache add build-base linux-headers git bash ca-certificates libstdc++ grep

FROM base AS test

WORKDIR /app

ADD go.mod go.mod
ADD go.sum go.sum
ADD erigon-lib/go.mod erigon-lib/go.mod
ADD erigon-lib/go.sum erigon-lib/go.sum
RUN go mod download

ADD . .

WORKDIR /app/test
ENTRYPOINT ["make"]
