[Log]
Level = "info"
Environment = "development"
Outputs = ["stderr"]

[SyncDB]
Database = "postgres"
    [SyncDB.PgStorage]
    User = "test_user"
    Name = "test_db"
    Password = "test_password"
    Host = "xlayer-bridge-db"
    Port = "5432"
    MaxConns = 20

[Etherman]
L1URL = "http://xlayer-mock-l1-network:8545"
L2URLs = ["http://xlayer-rpc:8545"]

[Synchronizer]
SyncInterval = "1s"
SyncChunkSize = 50
ForceL2SyncChunk = true

[BridgeController]
Height = 32

[BridgeServer]
GRPCPort = "9090"
HTTPPort = "8080"
DefaultPageLimit = 25
MaxPageLimit = 20000
FinalizedGEREnabled = false
    [BridgeServer.DB]
    Database = "postgres"
        [BridgeServer.DB.PgStorage]
        User = "test_user"
        Name = "test_db"
        Password = "test_password"
        Host = "xlayer-bridge-db"
        Port = "5432"
        MaxConns = 20

[NetworkConfig]
GenBlockNumber = 0
PolygonBridgeAddress = "0x3a277Fa4E78cc1266F32E26c467F99A8eAEfF7c3"
PolygonZkEVMGlobalExitRootAddress = "0xB8cedD4B9eF683f0887C44a6E4312dC7A6e2fcdB"
PolygonRollupManagerAddress = "0x2d42E2899662EFf08b13eeb65b154b904C7a1c8a"
PolygonZkEVMAddress = "0xeb173087729c88a47568AF87b17C653039377BA6"
L2PolygonBridgeAddresses = ["0x3a277Fa4E78cc1266F32E26c467F99A8eAEfF7c3"]
RequireSovereignChainSmcs = [false]
L2PolygonZkEVMGlobalExitRootAddresses = ["0xa40d5f56745a118d0906a34e69aec8c0db1cb8fa"]

[ClaimTxManager]
Enabled = true
FrequencyToMonitorTxs = "5s"
PrivateKey = {Path = "/pk/keystore.claimtxmanager", Password = "testonly"}
RetryInterval = "1s"
RetryNumber = 10

[Metrics]
Enabled = true
Host = "0.0.0.0"
Port = "8090"
