networks:
  default:
    name: erigon
services:
  xlayer-approve:
    container_name: xlayer-approve
    image: hermeznetwork/zkevm-node:v0.6.6
    volumes:
      - ./keystore/sequencer.keystore:/pk/keystore
      - ./config/test.node.config.toml:/app/config.toml
      - ./config/test.genesis.config.json:/app/genesis.json
    command:
      - "/bin/sh"
      - "-c"
      - "/app/zkevm-node approve --network custom --custom-network-file /app/genesis.json --key-store-path /pk/keystore --pw testonly --am 115792089237316195423570985008687907853269984665640564039457584007913129639935 -y --cfg /app/config.toml"

  xlayer-seq:
    container_name: xlayer-seq
    image: cdk-erigon
    environment:
      - CDK_ERIGON_SEQUENCER=1
      - WRITE_MAP=true
    ports:
      - 6060:6060
      - 8123:8545
      - 6900:6900
      - 9092:9095
    volumes:
      - ./data/seq/:/home/erigon/data/
      - ./config/test.erigon.seq.config.yaml:/usr/src/app/config.yaml
      - ./config/dynamic-mynetwork-allocs.json:/usr/src/app/dynamic-mynetwork-allocs.json
      - ./config/dynamic-mynetwork-chainspec.json:/usr/src/app/dynamic-mynetwork-chainspec.json
      - ./config/dynamic-mynetwork-conf.json:/usr/src/app/dynamic-mynetwork-conf.json
    command: >
      cdk-erigon --http.vhosts=* --http.corsdomain=* --ws --config=/usr/src/app/config.yaml

  xlayer-mock-l1-network:
    container_name: xlayer-mock-l1-network
    image: hermeznetwork/geth-zkevm-contracts:1.5-integration
    ports:
      - 8545:8545
      - 8546:8546
    command:
      - "--http"
      - "--http.api"
      - "admin,eth,debug,miner,net,txpool,personal,web3"
      - "--http.addr"
      - "0.0.0.0"
      - "--http.corsdomain"
      - "*"
      - "--http.vhosts"
      - "*"
      - "--ws"
      - "--ws.origins"
      - "*"
      - "--ws.addr"
      - "0.0.0.0"
      - "--dev"
      - "--dev.period"
      - "12"
      - "--dev.gaslimit"
      - "100000000"
      - "--datadir"
      - "/geth_data"
      - "--syncmode"
      - "full"
      - "--rpc.allow-unprotected-txs"
      - "--miner.gaslimit"
      - "100000000"
      - "--rpc.txfeecap"
      - "0"
      - "--rpc.gascap"
      - "100000000"
      - "--txpool.globalslots"
      - "20000"
      - "--txpool.globalqueue"
      - "10000"

  xlayer-bridge-db:
    container_name: xlayer-bridge-db
    image: postgres:15
    deploy:
      resources:
        limits:
          memory: 2G
        reservations:
          memory: 1G
    ports:
      - 5439:5432
    environment:
      - POSTGRES_USER=test_user
      - POSTGRES_PASSWORD=test_password
      - POSTGRES_DB=test_db
    command: [ "postgres", "-N", "500" ]

  xlayer-bridge-service:
    container_name: xlayer-bridge-service
    image: zkevm-bridge-service:latest
    ports:
      - 8080:8080
      - 9090:9090
    environment:
      - ZKEVM_BRIDGE_DATABASE_USER=test_user
      - ZKEVM_BRIDGE_DATABASE_PASSWORD=test_password
      - ZKEVM_BRIDGE_DATABASE_NAME=test_db
      - ZKEVM_BRIDGE_DATABASE_HOST=xlayer-bridge-db
      - ZKEVM_BRIDGE_DATABASE_PORT=5432
    volumes:
      - ./keystore/sequencer.keystore:/pk/keystore.claimtxmanager
      - ./config/test.bridge.config.toml:/app/config.toml
    command:
      - "/bin/sh"
      - "-c"
      - "/app/zkevm-bridge run --cfg /app/config.toml"

  xlayer-bridge-ui:
    container_name: xlayer-bridge-ui
    image: hermeznetwork/zkevm-bridge-ui:latest
    ports:
      - 8090:80
    environment:
      - ETHEREUM_RPC_URL=http://127.0.0.1:8545
      - ETHEREUM_EXPLORER_URL=http://127.0.0.1:4000
      - ETHEREUM_ROLLUP_MANAGER_ADDRESS=0x2d42E2899662EFf08b13eeb65b154b904C7a1c8a
      - ETHEREUM_BRIDGE_CONTRACT_ADDRESS=0x3a277Fa4E78cc1266F32E26c467F99A8eAEfF7c3
      - ETHEREUM_FORCE_UPDATE_GLOBAL_EXIT_ROOT=true
      - ETHEREUM_PROOF_OF_EFFICIENCY_CONTRACT_ADDRESS=0xeb173087729c88a47568AF87b17C653039377BA6
      - POLYGON_ZK_EVM_RPC_URL=http://127.0.0.1:8123
      - POLYGON_ZK_EVM_EXPLORER_URL=http://127.0.0.1:4001
      - POLYGON_ZK_EVM_BRIDGE_CONTRACT_ADDRESS=0x3a277Fa4E78cc1266F32E26c467F99A8eAEfF7c3
      - POLYGON_ZK_EVM_NETWORK_ID=1
      - BRIDGE_API_URL=http://127.0.0.1:8080
      - ENABLE_FIAT_EXCHANGE_RATES=false
      - ENABLE_OUTDATED_NETWORK_MODAL=false
      - ENABLE_DEPOSIT_WARNING=false
      - ENABLE_REPORT_FORM=false
      - RESOLVE_RELATIVE_URLS=false

  xlayer-pool-db:
    container_name: xlayer-pool-db
    image: postgres:15
    ports:
      - 5440:5432
    volumes:
      - /var/lib/postgresql/data
    environment:
      - POSTGRES_USER=pool_user
      - POSTGRES_PASSWORD=pool_password
      - POSTGRES_DB=pool_db
    command:
      - "postgres"
      - "-N"
      - "500"

  xlayer-pool-manager:
    container_name: xlayer-pool-manager
    image: hermeznetwork/zkevm-pool-manager:v0.1.2
    deploy:
      resources:
        limits:
          memory: 1G
        reservations:
          memory: 512M
    ports:
      - 8125:8545
    volumes:
      - ./config/test.poolmanager.toml:/app/poolmanager.toml
    command:
      - "/bin/sh"
      - "-c"
      - "/app/zkevm-pool-manager run --cfg /app/poolmanager.toml"

  xlayer-aggkit:
    container_name: xlayer-aggkit
    image: aggkit:local
    restart: on-failure
    volumes:
      - ./data/aggkit:/tmp
      - ./keystore/aggregator.keystore:/etc/aggkit/aggregator.keystore
      - ./keystore/sequencer.keystore:/etc/aggkit/sequencer.keystore
      - ./config/aggkit.toml:/etc/aggkit/aggkit.toml
      - ./config/test.genesis.config.json:/etc/aggkit/genesis.json
    ports:
      - 5576:5576
    command: ["run", "--cfg=/etc/aggkit/aggkit.toml", "--components=aggsender"]

  xlayer-agglayer:
    container_name: xlayer-agglayer
    image: zjg555543/agglayer:upstream-v0.3.3
    # image: zjg555543/agglayer:upstream-v0.3.0-rc.16
    ports:
      - 4443:4443
      - 4444:4444
      - 4446:4446
      - 9094:9092
    volumes:
      - ./keystore/agglayer.keystore:/etc/zkevm/agglayer.keystore
      - ./config/agglayer-config.toml:/etc/zkevm/agglayer-config.toml
      - ./data/agglayer/storage:/etc/zkevm/storage/
      - ./data/agglayer/backups:/etc/zkevm/backups/
    command:
      - "/bin/sh"
      - "-c"
      - "/usr/local/bin/agglayer run --cfg /etc/zkevm/agglayer-config.toml"

  xlayer-agglayer-prover:
    container_name: xlayer-agglayer-prover
    image: zjg555543/agglayer:upstream-v0.3.3
    environment:
      - NETWORK_RPC_URL=https://rpc.production.succinct.xyz
      - RUST_BACKTRACE=1
      - SP1_PRIVATE_KEY=
      - NETWORK_PRIVATE_KEY=
      - SP1_PROVER=network
      # - RUST_LOG=debug
    volumes:
      - ./config/agglayer-prover-config.toml:/etc/zkevm/agglayer-prover-config.toml
    ports:
      - 4445:4445
      - 9093:9093
    command:
      - "/bin/sh"
      - "-c"
      - "/usr/local/bin/agglayer prover --cfg /etc/zkevm/agglayer-prover-config.toml"

  xlayer-agg-db-old:
    container_name: xlayer-agg-db-old
    image: postgres:15
    deploy:
      resources:
        limits:
          memory: 2G
        reservations:
          memory: 1G
    ports:
      - 15434:5432
    environment:
      - POSTGRES_USER=aggregator_user
      - POSTGRES_PASSWORD=aggregator_password
      - POSTGRES_DB=aggregator_db
    command:
      - "postgres"
      - "-N"
      - "500"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U aggregator_user -d aggregator_db"]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 5s

  xlayer-rpc:
    container_name: xlayer-rpc
    image: cdk-erigon
    environment:
      - CDK_ERIGON_SEQUENCER=0
      - WRITE_MAP=true
    ports:
      - 6061:6060
      - 8124:8545
      - 6901:6900
      - 9091:9095
    volumes:
      - ./data/rpc/:/home/erigon/data/
      - ./config/test.erigon.rpc.config.yaml:/usr/src/app/config.yaml
      - ./config/dynamic-mynetwork-allocs.json:/usr/src/app/dynamic-mynetwork-allocs.json
      - ./config/dynamic-mynetwork-chainspec.json:/usr/src/app/dynamic-mynetwork-chainspec.json
      - ./config/dynamic-mynetwork-conf.json:/usr/src/app/dynamic-mynetwork-conf.json
    command: >
      cdk-erigon --http.vhosts=* --http.corsdomain=* --ws --config=/usr/src/app/config.yaml

  xlayer-da:
    container_name: xlayer-da
    image: zjg555543/xlayer-da:merge-v0.0.10
    ports:
      - 8444:8444
    volumes:
      - ./config/test.da.toml:/app/config.toml
      - ./keystore/test-member.keystore:/pk/test-member.keystore
    command:
      - "/bin/sh"
      - "-c"
      - "/app/xlayer-data-availability run --cfg /app/config.toml"

  xlayer-da-db:
    container_name: xlayer-da-db
    image: postgres:15
    ports:
      - 5438:5432
    environment:
      - POSTGRES_USER=committee_user
      - POSTGRES_PASSWORD=committee_password
      - POSTGRES_DB=committee_db
    command:
      - "postgres"
      - "-N"
      - "500"


  xlayer-seqs:
    container_name: xlayer-seqs
    image: zjg555543/cdk:v0.5.4-rc1
    volumes:
      - ./data/seqs:/tmp/cdk
      - ./keystore/da.permit.keystore:/pk/da.permit.keystore
      - ./keystore/sequencer.keystore:/pk/sequencer.keystore
      - ./config/cdk.config-old.toml:/app/config.toml
      - ./config/test.genesis.config.json:/app/genesis.json
    command:
      - "/bin/sh"
      - "-c"
      - "/usr/local/bin/cdk-node run --cfg /app/config.toml --custom-network-file /app/genesis.json --components sequence-sender"

  xlayer-agg:
    container_name: xlayer-agg
    image: zjg555543/cdk:v0.5.4-rc1
    ports:
      - 50081:50081
    volumes:
      - ./data/agg:/tmp/cdk
      - ./keystore/aggregator.keystore:/pk/aggregator.keystore
      - ./keystore/sequencer.keystore:/pk/sequencer.keystore
      - ./config/cdk.config-old.toml:/app/config.toml
      - ./config/test.genesis.config.json:/app/genesis.json
    command:
      - "/bin/sh"
      - "-c"
      - "/usr/local/bin/cdk-node run --cfg /app/config.toml --custom-network-file /app/genesis.json  --components aggregator"

  xlayer-prover-old:
    container_name: xlayer-prover-old
    image: hermeznetwork/zkevm-prover:v9.0.0-RC3-fork.13
    platform: linux/amd64
    environment:
      - EXPERIMENTAL_DOCKER_DESKTOP_FORCE_QEMU=1
    volumes:
      - ./config/test.prover.config.json:/usr/src/app/config.json
    command: >
      zkProver -c /usr/src/app/config.json