networks:
  default:
    name: rpcs
    external: true

services:
  xlayer-bridge-db:
    container_name: xlayer-bridge-db
    image: postgres:15
    deploy:
      resources:
        limits:
          memory: 2G
        reservations:
          memory: 1G
    ports:
      - 5439:5432
    environment:
      - POSTGRES_USER=test_user
      - POSTGRES_PASSWORD=test_password
      - POSTGRES_DB=test_db
    command: [ "postgres", "-N", "500" ]
    volumes:
      - ./bridge-db:/var/lib/postgresql/data

  xlayer-bridge-service:
    container_name: xlayer-bridge-service
    image: hermeznetwork/zkevm-bridge-service:v0.6.0-RC16
    ports:
      - 8080:8080
      - 9090:9090
    environment:
      - ZKEVM_BRIDGE_DATABASE_USER=test_user
      - ZKEVM_BRIDGE_DATABASE_PASSWORD=test_password
      - ZKEVM_BRIDGE_DATABASE_NAME=test_db
      - ZKEVM_BRIDGE_DATABASE_HOST=xlayer-bridge-db
      - ZKEVM_BRIDGE_DATABASE_PORT=5432
    volumes:
      - ./conf/sequencer.keystore:/pk/keystore.claimtxmanager
      - ./conf/test.bridge.config.toml:/app/config.toml
    command:
      - "/bin/sh"
      - "-c"
      - "/app/zkevm-bridge run --cfg /app/config.toml"

  xlayer-mainnet-rpc:
    container_name: xlayer-mainnet-rpc
    image: cdk-erigon-dev-v23
    environment:
      - CDK_ERIGON_SEQUENCER=0
    ports:
      - 46061:6060
      - 48124:8545
      - 46901:6900
      - 49091:9095
    restart: always
    volumes:
      - ./rpc:/home/erigon/data/
      - ./conf/xlayerconfig-mainnet-rpc.yaml:/usr/src/app/config.yaml
    command: >
      cdk-erigon --http.vhosts=* --http.corsdomain=* --ws --config=/usr/src/app/config.yaml

  xlayer-bridge-ui:
    container_name: xlayer-bridge-ui
    image: hermeznetwork/zkevm-bridge-ui:latest
    ports:
      - 8090:80
    environment:
      - ETHEREUM_RPC_URL=http://127.0.0.1:8545
      - ETHEREUM_EXPLORER_URL=http://127.0.0.1:4000
      - ETHEREUM_ROLLUP_MANAGER_ADDRESS=0xE96dBF374555C6993618906629988d39184716B3
      - ETHEREUM_BRIDGE_CONTRACT_ADDRESS=0x4B24266C13AFEf2bb60e2C69A4C08A482d81e3CA
      - ETHEREUM_FORCE_UPDATE_GLOBAL_EXIT_ROOT=true
      - ETHEREUM_PROOF_OF_EFFICIENCY_CONTRACT_ADDRESS=0xE45CCD0757670580a4a3600DE5cef1e45F0Ec2bd
      - POLYGON_ZK_EVM_RPC_URL=http://127.0.0.1:8123
      - POLYGON_ZK_EVM_EXPLORER_URL=http://127.0.0.1:4001
      - POLYGON_ZK_EVM_BRIDGE_CONTRACT_ADDRESS=0x4B24266C13AFEf2bb60e2C69A4C08A482d81e3CA
      - POLYGON_ZK_EVM_NETWORK_ID=1
      - BRIDGE_API_URL=http://127.0.0.1:8080
      - ENABLE_FIAT_EXCHANGE_RATES=false
      - ENABLE_OUTDATED_NETWORK_MODAL=false
      - ENABLE_DEPOSIT_WARNING=false
      - ENABLE_REPORT_FORM=false
      - RESOLVE_RELATIVE_URLS=false
  