prover-entrypoint = "http://agglayer-prover:4445"
debug-mode = true

[full-node-rpcs]

[proof-signers]

[rpc]
grpc-port = 4443
readrpc-port = 4444
admin-port = 4446
host = "0.0.0.0"
request-timeout = 180
max-request-body-size = 104857600

[prover.grpc]
max-decoding-message-size = 1073741824
max-encoding-message-size = 1073741824

[grpc]
max-decoding-message-size = 1073741824
max-encoding-message-size = 1073741824

[outbound.rpc.settle]
max-retries = 3
retry-interval = 7
confirmations = 1
settlement-timeout = 1200

[log]
level = "debug"
outputs = ["stderr"]
format = "json"

[auth.local]
private-keys = [
    { path = "/etc/agglayer/agglayer.keystore", password = "randompassword" },
]

[l1]
chain-id = 1
node-url = "http://anvil:8545"
ws-node-url = "ws://anvil:8545"
rollup-manager-contract = "0x5132A183E9F3CB7C848b0AAC5Ae0c4f0491B7aB2"
polygon-zkevm-global-exit-root-v2-contract = "0x580bda1e7A0CFAe92Fa7F6c20A3794F169CE3CFb"
rpc-timeout = 45

[l2]
rpc-timeout = 45

[telemetry]
prometheus-addr = "0.0.0.0:9092"

[rate-limiting]
send-tx = "unlimited"

[rate-limiting.network]

[epoch.block-clock]
epoch-duration = 300
genesis-block = 21766615

[shutdown]
runtime-timeout = 5

[certificate-orchestrator]
input-backpressure-buffer-size = 1000

[certificate-orchestrator.prover.sp1-local]

[storage]
db-path = "/var/agglayer/storage"
