// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: realtime.proto

package realtime

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RealtimeTransactionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RealtimeTransactionRequest) Reset() {
	*x = RealtimeTransactionRequest{}
	mi := &file_realtime_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RealtimeTransactionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RealtimeTransactionRequest) ProtoMessage() {}

func (x *RealtimeTransactionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_realtime_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RealtimeTransactionRequest.ProtoReflect.Descriptor instead.
func (*RealtimeTransactionRequest) Descriptor() ([]byte, []int) {
	return file_realtime_proto_rawDescGZIP(), []int{0}
}

type RealtimeTransactionReply struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	RlpTransaction []byte                 `protobuf:"bytes,1,opt,name=rlp_transaction,json=rlpTransaction,proto3" json:"rlp_transaction,omitempty"`
	RlpReceipt     []byte                 `protobuf:"bytes,2,opt,name=rlp_receipt,json=rlpReceipt,proto3" json:"rlp_receipt,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *RealtimeTransactionReply) Reset() {
	*x = RealtimeTransactionReply{}
	mi := &file_realtime_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RealtimeTransactionReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RealtimeTransactionReply) ProtoMessage() {}

func (x *RealtimeTransactionReply) ProtoReflect() protoreflect.Message {
	mi := &file_realtime_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RealtimeTransactionReply.ProtoReflect.Descriptor instead.
func (*RealtimeTransactionReply) Descriptor() ([]byte, []int) {
	return file_realtime_proto_rawDescGZIP(), []int{1}
}

func (x *RealtimeTransactionReply) GetRlpTransaction() []byte {
	if x != nil {
		return x.RlpTransaction
	}
	return nil
}

func (x *RealtimeTransactionReply) GetRlpReceipt() []byte {
	if x != nil {
		return x.RlpReceipt
	}
	return nil
}

type RealtimeLogsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RealtimeLogsRequest) Reset() {
	*x = RealtimeLogsRequest{}
	mi := &file_realtime_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RealtimeLogsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RealtimeLogsRequest) ProtoMessage() {}

func (x *RealtimeLogsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_realtime_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RealtimeLogsRequest.ProtoReflect.Descriptor instead.
func (*RealtimeLogsRequest) Descriptor() ([]byte, []int) {
	return file_realtime_proto_rawDescGZIP(), []int{2}
}

type RealtimeLogsReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RlpLogs       []byte                 `protobuf:"bytes,1,opt,name=rlp_logs,json=rlpLogs,proto3" json:"rlp_logs,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RealtimeLogsReply) Reset() {
	*x = RealtimeLogsReply{}
	mi := &file_realtime_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RealtimeLogsReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RealtimeLogsReply) ProtoMessage() {}

func (x *RealtimeLogsReply) ProtoReflect() protoreflect.Message {
	mi := &file_realtime_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RealtimeLogsReply.ProtoReflect.Descriptor instead.
func (*RealtimeLogsReply) Descriptor() ([]byte, []int) {
	return file_realtime_proto_rawDescGZIP(), []int{3}
}

func (x *RealtimeLogsReply) GetRlpLogs() []byte {
	if x != nil {
		return x.RlpLogs
	}
	return nil
}

var File_realtime_proto protoreflect.FileDescriptor

const file_realtime_proto_rawDesc = "" +
	"\n" +
	"\x0erealtime.proto\x12\brealtime\"\x1c\n" +
	"\x1aRealtimeTransactionRequest\"d\n" +
	"\x18RealtimeTransactionReply\x12'\n" +
	"\x0frlp_transaction\x18\x01 \x01(\fR\x0erlpTransaction\x12\x1f\n" +
	"\vrlp_receipt\x18\x02 \x01(\fR\n" +
	"rlpReceipt\"\x15\n" +
	"\x13RealtimeLogsRequest\".\n" +
	"\x11RealtimeLogsReply\x12\x19\n" +
	"\brlp_logs\x18\x01 \x01(\fR\arlpLogs2\xbf\x01\n" +
	"\bRealtime\x12c\n" +
	"\x15OnRealtimeTransaction\x12$.realtime.RealtimeTransactionRequest\x1a\".realtime.RealtimeTransactionReply0\x01\x12N\n" +
	"\x0eOnRealtimeLogs\x12\x1d.realtime.RealtimeLogsRequest\x1a\x1b.realtime.RealtimeLogsReply0\x01B\fZ\n" +
	"./realtimeb\x06proto3"

var (
	file_realtime_proto_rawDescOnce sync.Once
	file_realtime_proto_rawDescData []byte
)

func file_realtime_proto_rawDescGZIP() []byte {
	file_realtime_proto_rawDescOnce.Do(func() {
		file_realtime_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_realtime_proto_rawDesc), len(file_realtime_proto_rawDesc)))
	})
	return file_realtime_proto_rawDescData
}

var file_realtime_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_realtime_proto_goTypes = []any{
	(*RealtimeTransactionRequest)(nil), // 0: realtime.RealtimeTransactionRequest
	(*RealtimeTransactionReply)(nil),   // 1: realtime.RealtimeTransactionReply
	(*RealtimeLogsRequest)(nil),        // 2: realtime.RealtimeLogsRequest
	(*RealtimeLogsReply)(nil),          // 3: realtime.RealtimeLogsReply
}
var file_realtime_proto_depIdxs = []int32{
	0, // 0: realtime.Realtime.OnRealtimeTransaction:input_type -> realtime.RealtimeTransactionRequest
	2, // 1: realtime.Realtime.OnRealtimeLogs:input_type -> realtime.RealtimeLogsRequest
	1, // 2: realtime.Realtime.OnRealtimeTransaction:output_type -> realtime.RealtimeTransactionReply
	3, // 3: realtime.Realtime.OnRealtimeLogs:output_type -> realtime.RealtimeLogsReply
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_realtime_proto_init() }
func file_realtime_proto_init() {
	if File_realtime_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_realtime_proto_rawDesc), len(file_realtime_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_realtime_proto_goTypes,
		DependencyIndexes: file_realtime_proto_depIdxs,
		MessageInfos:      file_realtime_proto_msgTypes,
	}.Build()
	File_realtime_proto = out.File
	file_realtime_proto_goTypes = nil
	file_realtime_proto_depIdxs = nil
}
