// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v5.29.3
// source: realtime.proto

package realtime

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	Realtime_OnRealtimeTransaction_FullMethodName = "/realtime.Realtime/OnRealtimeTransaction"
	Realtime_OnRealtimeLogs_FullMethodName        = "/realtime.Realtime/OnRealtimeLogs"
)

// RealtimeClient is the client API for Realtime service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type RealtimeClient interface {
	// OnRealtimeTransaction streams real-time transaction data, including the RLP-encoded transaction, receipt, and internal transactions.
	OnRealtimeTransaction(ctx context.Context, in *RealtimeTransactionRequest, opts ...grpc.CallOption) (Realtime_OnRealtimeTransactionClient, error)
	// OnRealtimeLogs streams real-time log data, providing RLP-encoded logs emitted by smart contracts.
	OnRealtimeLogs(ctx context.Context, in *RealtimeLogsRequest, opts ...grpc.CallOption) (Realtime_OnRealtimeLogsClient, error)
}

type realtimeClient struct {
	cc grpc.ClientConnInterface
}

func NewRealtimeClient(cc grpc.ClientConnInterface) RealtimeClient {
	return &realtimeClient{cc}
}

func (c *realtimeClient) OnRealtimeTransaction(ctx context.Context, in *RealtimeTransactionRequest, opts ...grpc.CallOption) (Realtime_OnRealtimeTransactionClient, error) {
	stream, err := c.cc.NewStream(ctx, &Realtime_ServiceDesc.Streams[0], Realtime_OnRealtimeTransaction_FullMethodName, opts...)
	if err != nil {
		return nil, err
	}
	x := &realtimeOnRealtimeTransactionClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type Realtime_OnRealtimeTransactionClient interface {
	Recv() (*RealtimeTransactionReply, error)
	grpc.ClientStream
}

type realtimeOnRealtimeTransactionClient struct {
	grpc.ClientStream
}

func (x *realtimeOnRealtimeTransactionClient) Recv() (*RealtimeTransactionReply, error) {
	m := new(RealtimeTransactionReply)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *realtimeClient) OnRealtimeLogs(ctx context.Context, in *RealtimeLogsRequest, opts ...grpc.CallOption) (Realtime_OnRealtimeLogsClient, error) {
	stream, err := c.cc.NewStream(ctx, &Realtime_ServiceDesc.Streams[1], Realtime_OnRealtimeLogs_FullMethodName, opts...)
	if err != nil {
		return nil, err
	}
	x := &realtimeOnRealtimeLogsClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type Realtime_OnRealtimeLogsClient interface {
	Recv() (*RealtimeLogsReply, error)
	grpc.ClientStream
}

type realtimeOnRealtimeLogsClient struct {
	grpc.ClientStream
}

func (x *realtimeOnRealtimeLogsClient) Recv() (*RealtimeLogsReply, error) {
	m := new(RealtimeLogsReply)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// RealtimeServer is the server API for Realtime service.
// All implementations must embed UnimplementedRealtimeServer
// for forward compatibility
type RealtimeServer interface {
	// OnRealtimeTransaction streams real-time transaction data, including the RLP-encoded transaction, receipt, and internal transactions.
	OnRealtimeTransaction(*RealtimeTransactionRequest, Realtime_OnRealtimeTransactionServer) error
	// OnRealtimeLogs streams real-time log data, providing RLP-encoded logs emitted by smart contracts.
	OnRealtimeLogs(*RealtimeLogsRequest, Realtime_OnRealtimeLogsServer) error
	mustEmbedUnimplementedRealtimeServer()
}

// UnimplementedRealtimeServer must be embedded to have forward compatible implementations.
type UnimplementedRealtimeServer struct {
}

func (UnimplementedRealtimeServer) OnRealtimeTransaction(*RealtimeTransactionRequest, Realtime_OnRealtimeTransactionServer) error {
	return status.Errorf(codes.Unimplemented, "method OnRealtimeTransaction not implemented")
}
func (UnimplementedRealtimeServer) OnRealtimeLogs(*RealtimeLogsRequest, Realtime_OnRealtimeLogsServer) error {
	return status.Errorf(codes.Unimplemented, "method OnRealtimeLogs not implemented")
}
func (UnimplementedRealtimeServer) mustEmbedUnimplementedRealtimeServer() {}

// UnsafeRealtimeServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to RealtimeServer will
// result in compilation errors.
type UnsafeRealtimeServer interface {
	mustEmbedUnimplementedRealtimeServer()
}

func RegisterRealtimeServer(s grpc.ServiceRegistrar, srv RealtimeServer) {
	s.RegisterService(&Realtime_ServiceDesc, srv)
}

func _Realtime_OnRealtimeTransaction_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(RealtimeTransactionRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(RealtimeServer).OnRealtimeTransaction(m, &realtimeOnRealtimeTransactionServer{stream})
}

type Realtime_OnRealtimeTransactionServer interface {
	Send(*RealtimeTransactionReply) error
	grpc.ServerStream
}

type realtimeOnRealtimeTransactionServer struct {
	grpc.ServerStream
}

func (x *realtimeOnRealtimeTransactionServer) Send(m *RealtimeTransactionReply) error {
	return x.ServerStream.SendMsg(m)
}

func _Realtime_OnRealtimeLogs_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(RealtimeLogsRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(RealtimeServer).OnRealtimeLogs(m, &realtimeOnRealtimeLogsServer{stream})
}

type Realtime_OnRealtimeLogsServer interface {
	Send(*RealtimeLogsReply) error
	grpc.ServerStream
}

type realtimeOnRealtimeLogsServer struct {
	grpc.ServerStream
}

func (x *realtimeOnRealtimeLogsServer) Send(m *RealtimeLogsReply) error {
	return x.ServerStream.SendMsg(m)
}

// Realtime_ServiceDesc is the grpc.ServiceDesc for Realtime service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Realtime_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "realtime.Realtime",
	HandlerType: (*RealtimeServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "OnRealtimeTransaction",
			Handler:       _Realtime_OnRealtimeTransaction_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "OnRealtimeLogs",
			Handler:       _Realtime_OnRealtimeLogs_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "realtime.proto",
}
