// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: realtime.proto

package realtime

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// RealtimeTransactionRequest is an empty message used as a placeholder for initiating the OnRealtimeTransaction stream.
// It may be extended in the future to include filtering criteria or other parameters.
type RealtimeTransactionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RealtimeTransactionRequest) Reset() {
	*x = RealtimeTransactionRequest{}
	mi := &file_realtime_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RealtimeTransactionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RealtimeTransactionRequest) ProtoMessage() {}

func (x *RealtimeTransactionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_realtime_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RealtimeTransactionRequest.ProtoReflect.Descriptor instead.
func (*RealtimeTransactionRequest) Descriptor() ([]byte, []int) {
	return file_realtime_proto_rawDescGZIP(), []int{0}
}

// RealtimeTransactionReply represents a message containing a transaction, its receipt, and internal transactions.
type RealtimeTransactionReply struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// RLP-encoded raw transaction data, representing the full transaction as serialized on the Ethereum blockchain.
	RlpTransaction []byte `protobuf:"bytes,1,opt,name=rlp_transaction,json=rlpTransaction,proto3" json:"rlp_transaction,omitempty"`
	// Transaction receipt, containing consensus and derived fields about the transaction's execution.
	Receipt *Receipt `protobuf:"bytes,2,opt,name=receipt,proto3" json:"receipt,omitempty"`
	// List of internal transactions or calls triggered during the transaction's execution.
	InnerTxs      []*InnerTx `protobuf:"bytes,3,rep,name=innerTxs,proto3" json:"innerTxs,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RealtimeTransactionReply) Reset() {
	*x = RealtimeTransactionReply{}
	mi := &file_realtime_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RealtimeTransactionReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RealtimeTransactionReply) ProtoMessage() {}

func (x *RealtimeTransactionReply) ProtoReflect() protoreflect.Message {
	mi := &file_realtime_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RealtimeTransactionReply.ProtoReflect.Descriptor instead.
func (*RealtimeTransactionReply) Descriptor() ([]byte, []int) {
	return file_realtime_proto_rawDescGZIP(), []int{1}
}

func (x *RealtimeTransactionReply) GetRlpTransaction() []byte {
	if x != nil {
		return x.RlpTransaction
	}
	return nil
}

func (x *RealtimeTransactionReply) GetReceipt() *Receipt {
	if x != nil {
		return x.Receipt
	}
	return nil
}

func (x *RealtimeTransactionReply) GetInnerTxs() []*InnerTx {
	if x != nil {
		return x.InnerTxs
	}
	return nil
}

// Log represents an event log emitted by a smart contract.
// Address of the contract that generated the event.
type Log struct {
	state   protoimpl.MessageState `protogen:"open.v1"`
	Address []byte                 `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"`
	// List of topics provided by the contract.
	Topics [][]byte `protobuf:"bytes,2,rep,name=topics,proto3" json:"topics,omitempty"`
	// Data supplied by the contract, usually ABI-encoded.
	Data []byte `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
	// Block number in which the transaction was included (derived, not consensus-secured).
	BlockNumber uint64 `protobuf:"varint,4,opt,name=blockNumber,proto3" json:"blockNumber,omitempty"`
	// Hash of the transaction.
	TransactionHash []byte `protobuf:"bytes,5,opt,name=transactionHash,proto3" json:"transactionHash,omitempty"`
	// Index of the transaction in the block.
	TransactionIndex uint64 `protobuf:"varint,6,opt,name=transactionIndex,proto3" json:"transactionIndex,omitempty"`
	// Hash of the block in which the transaction was included.
	BlockHash []byte `protobuf:"bytes,7,opt,name=blockHash,proto3" json:"blockHash,omitempty"`
	// Index of the log in the block.
	LogIndex uint64 `protobuf:"varint,8,opt,name=logIndex,proto3" json:"logIndex,omitempty"`
	// True if this log was reverted due to a chain reorganization.
	Removed       bool `protobuf:"varint,9,opt,name=removed,proto3" json:"removed,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Log) Reset() {
	*x = Log{}
	mi := &file_realtime_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Log) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Log) ProtoMessage() {}

func (x *Log) ProtoReflect() protoreflect.Message {
	mi := &file_realtime_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Log.ProtoReflect.Descriptor instead.
func (*Log) Descriptor() ([]byte, []int) {
	return file_realtime_proto_rawDescGZIP(), []int{2}
}

func (x *Log) GetAddress() []byte {
	if x != nil {
		return x.Address
	}
	return nil
}

func (x *Log) GetTopics() [][]byte {
	if x != nil {
		return x.Topics
	}
	return nil
}

func (x *Log) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *Log) GetBlockNumber() uint64 {
	if x != nil {
		return x.BlockNumber
	}
	return 0
}

func (x *Log) GetTransactionHash() []byte {
	if x != nil {
		return x.TransactionHash
	}
	return nil
}

func (x *Log) GetTransactionIndex() uint64 {
	if x != nil {
		return x.TransactionIndex
	}
	return 0
}

func (x *Log) GetBlockHash() []byte {
	if x != nil {
		return x.BlockHash
	}
	return nil
}

func (x *Log) GetLogIndex() uint64 {
	if x != nil {
		return x.LogIndex
	}
	return 0
}

func (x *Log) GetRemoved() bool {
	if x != nil {
		return x.Removed
	}
	return false
}

// Receipt represents a transaction receipt.
// Transaction type (as defined in the Ethereum Yellow Paper).
type Receipt struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Type  uint32                 `protobuf:"varint,1,opt,name=type,proto3" json:"type,omitempty"`
	// Post-state root (post-transaction state).
	Root []byte `protobuf:"bytes,2,opt,name=root,proto3" json:"root,omitempty"`
	// Status of the transaction (success or failure).
	Status uint64 `protobuf:"varint,3,opt,name=status,proto3" json:"status,omitempty"`
	// Cumulative gas used in the block up to this transaction.
	CumulativeGasUsed uint64 `protobuf:"varint,4,opt,name=cumulativeGasUsed,proto3" json:"cumulativeGasUsed,omitempty"`
	// Bloom filter for the logs.
	LogsBloom []byte `protobuf:"bytes,5,opt,name=logsBloom,proto3" json:"logsBloom,omitempty"`
	// List of logs emitted by the transaction.
	Logs []*Log `protobuf:"bytes,6,rep,name=logs,proto3" json:"logs,omitempty"`
	// Hash of the transaction.
	TransactionHash []byte `protobuf:"bytes,7,opt,name=transactionHash,proto3" json:"transactionHash,omitempty"`
	// Address of the contract created, if any.
	ContractAddress []byte `protobuf:"bytes,8,opt,name=contractAddress,proto3" json:"contractAddress,omitempty"`
	// Gas used by this transaction.
	GasUsed uint64 `protobuf:"varint,9,opt,name=gasUsed,proto3" json:"gasUsed,omitempty"`
	// Hash of the block containing the transaction.
	BlockHash []byte `protobuf:"bytes,10,opt,name=blockHash,proto3" json:"blockHash,omitempty"`
	// Block number containing the transaction.
	BlockNumber string `protobuf:"bytes,11,opt,name=blockNumber,proto3" json:"blockNumber,omitempty"` // Using string for big.Int
	// Index of the transaction in the block.
	TransactionIndex uint64 `protobuf:"varint,12,opt,name=transactionIndex,proto3" json:"transactionIndex,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *Receipt) Reset() {
	*x = Receipt{}
	mi := &file_realtime_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Receipt) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Receipt) ProtoMessage() {}

func (x *Receipt) ProtoReflect() protoreflect.Message {
	mi := &file_realtime_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Receipt.ProtoReflect.Descriptor instead.
func (*Receipt) Descriptor() ([]byte, []int) {
	return file_realtime_proto_rawDescGZIP(), []int{3}
}

func (x *Receipt) GetType() uint32 {
	if x != nil {
		return x.Type
	}
	return 0
}

func (x *Receipt) GetRoot() []byte {
	if x != nil {
		return x.Root
	}
	return nil
}

func (x *Receipt) GetStatus() uint64 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *Receipt) GetCumulativeGasUsed() uint64 {
	if x != nil {
		return x.CumulativeGasUsed
	}
	return 0
}

func (x *Receipt) GetLogsBloom() []byte {
	if x != nil {
		return x.LogsBloom
	}
	return nil
}

func (x *Receipt) GetLogs() []*Log {
	if x != nil {
		return x.Logs
	}
	return nil
}

func (x *Receipt) GetTransactionHash() []byte {
	if x != nil {
		return x.TransactionHash
	}
	return nil
}

func (x *Receipt) GetContractAddress() []byte {
	if x != nil {
		return x.ContractAddress
	}
	return nil
}

func (x *Receipt) GetGasUsed() uint64 {
	if x != nil {
		return x.GasUsed
	}
	return 0
}

func (x *Receipt) GetBlockHash() []byte {
	if x != nil {
		return x.BlockHash
	}
	return nil
}

func (x *Receipt) GetBlockNumber() string {
	if x != nil {
		return x.BlockNumber
	}
	return ""
}

func (x *Receipt) GetTransactionIndex() uint64 {
	if x != nil {
		return x.TransactionIndex
	}
	return 0
}

// InnerTx represents an internal transaction or call.
// Depth of the transaction in the call stack.
type InnerTx struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Dept  string                 `protobuf:"bytes,1,opt,name=dept,proto3" json:"dept,omitempty"` // Using string for big.Int
	// Internal index of the transaction.
	InternalIndex string `protobuf:"bytes,2,opt,name=internal_index,json=internalIndex,proto3" json:"internal_index,omitempty"` // Using string for big.Int
	// Type of the call (e.g., CALL, DELEGATECALL).
	CallType string `protobuf:"bytes,3,opt,name=call_type,json=callType,proto3" json:"call_type,omitempty"`
	// Name of the function or call.
	Name string `protobuf:"bytes,4,opt,name=name,proto3" json:"name,omitempty"`
	// Trace address of the call in the execution trace.
	TraceAddress string `protobuf:"bytes,5,opt,name=trace_address,json=traceAddress,proto3" json:"trace_address,omitempty"`
	// Address of the code being executed.
	CodeAddress string `protobuf:"bytes,6,opt,name=code_address,json=codeAddress,proto3" json:"code_address,omitempty"`
	// Sender address.
	From string `protobuf:"bytes,7,opt,name=from,proto3" json:"from,omitempty"`
	// Recipient address.
	To string `protobuf:"bytes,8,opt,name=to,proto3" json:"to,omitempty"`
	// Input data for the call.
	Input string `protobuf:"bytes,9,opt,name=input,proto3" json:"input,omitempty"`
	// Output data from the call.
	Output string `protobuf:"bytes,10,opt,name=output,proto3" json:"output,omitempty"`
	// Whether the call resulted in an error.
	IsError bool `protobuf:"varint,11,opt,name=is_error,json=isError,proto3" json:"is_error,omitempty"`
	// Gas allocated for the call.
	Gas uint64 `protobuf:"varint,12,opt,name=gas,proto3" json:"gas,omitempty"`
	// Gas used by the call.
	GasUsed uint64 `protobuf:"varint,13,opt,name=gas_used,json=gasUsed,proto3" json:"gas_used,omitempty"`
	// Value transferred in the call (in Ether or token units).
	Value string `protobuf:"bytes,14,opt,name=value,proto3" json:"value,omitempty"`
	// Value in Wei.
	ValueWei string `protobuf:"bytes,15,opt,name=value_wei,json=valueWei,proto3" json:"value_wei,omitempty"`
	// Call value in Wei.
	CallValueWei string `protobuf:"bytes,16,opt,name=call_value_wei,json=callValueWei,proto3" json:"call_value_wei,omitempty"`
	// Error message, if any.
	Error         string `protobuf:"bytes,17,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InnerTx) Reset() {
	*x = InnerTx{}
	mi := &file_realtime_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InnerTx) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InnerTx) ProtoMessage() {}

func (x *InnerTx) ProtoReflect() protoreflect.Message {
	mi := &file_realtime_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InnerTx.ProtoReflect.Descriptor instead.
func (*InnerTx) Descriptor() ([]byte, []int) {
	return file_realtime_proto_rawDescGZIP(), []int{4}
}

func (x *InnerTx) GetDept() string {
	if x != nil {
		return x.Dept
	}
	return ""
}

func (x *InnerTx) GetInternalIndex() string {
	if x != nil {
		return x.InternalIndex
	}
	return ""
}

func (x *InnerTx) GetCallType() string {
	if x != nil {
		return x.CallType
	}
	return ""
}

func (x *InnerTx) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *InnerTx) GetTraceAddress() string {
	if x != nil {
		return x.TraceAddress
	}
	return ""
}

func (x *InnerTx) GetCodeAddress() string {
	if x != nil {
		return x.CodeAddress
	}
	return ""
}

func (x *InnerTx) GetFrom() string {
	if x != nil {
		return x.From
	}
	return ""
}

func (x *InnerTx) GetTo() string {
	if x != nil {
		return x.To
	}
	return ""
}

func (x *InnerTx) GetInput() string {
	if x != nil {
		return x.Input
	}
	return ""
}

func (x *InnerTx) GetOutput() string {
	if x != nil {
		return x.Output
	}
	return ""
}

func (x *InnerTx) GetIsError() bool {
	if x != nil {
		return x.IsError
	}
	return false
}

func (x *InnerTx) GetGas() uint64 {
	if x != nil {
		return x.Gas
	}
	return 0
}

func (x *InnerTx) GetGasUsed() uint64 {
	if x != nil {
		return x.GasUsed
	}
	return 0
}

func (x *InnerTx) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

func (x *InnerTx) GetValueWei() string {
	if x != nil {
		return x.ValueWei
	}
	return ""
}

func (x *InnerTx) GetCallValueWei() string {
	if x != nil {
		return x.CallValueWei
	}
	return ""
}

func (x *InnerTx) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

// RealtimeLogsRequest is an empty message used as a placeholder for initiating the OnRealtimeLogs stream.
// It may be extended in the future to include filtering criteria for logs (e.g., by address or topics).
type RealtimeLogsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RealtimeLogsRequest) Reset() {
	*x = RealtimeLogsRequest{}
	mi := &file_realtime_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RealtimeLogsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RealtimeLogsRequest) ProtoMessage() {}

func (x *RealtimeLogsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_realtime_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RealtimeLogsRequest.ProtoReflect.Descriptor instead.
func (*RealtimeLogsRequest) Descriptor() ([]byte, []int) {
	return file_realtime_proto_rawDescGZIP(), []int{5}
}

// RealtimeLogsReply represents a message containing RLP-encoded logs.
type RealtimeLogsReply struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// RLP-encoded log data, representing the serialized form of logs emitted by smart contracts.
	RlpLogs       []byte `protobuf:"bytes,1,opt,name=rlp_logs,json=rlpLogs,proto3" json:"rlp_logs,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RealtimeLogsReply) Reset() {
	*x = RealtimeLogsReply{}
	mi := &file_realtime_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RealtimeLogsReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RealtimeLogsReply) ProtoMessage() {}

func (x *RealtimeLogsReply) ProtoReflect() protoreflect.Message {
	mi := &file_realtime_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RealtimeLogsReply.ProtoReflect.Descriptor instead.
func (*RealtimeLogsReply) Descriptor() ([]byte, []int) {
	return file_realtime_proto_rawDescGZIP(), []int{6}
}

func (x *RealtimeLogsReply) GetRlpLogs() []byte {
	if x != nil {
		return x.RlpLogs
	}
	return nil
}

var File_realtime_proto protoreflect.FileDescriptor

const file_realtime_proto_rawDesc = "" +
	"\n" +
	"\x0erealtime.proto\x12\brealtime\"\x1c\n" +
	"\x1aRealtimeTransactionRequest\"\x9f\x01\n" +
	"\x18RealtimeTransactionReply\x12'\n" +
	"\x0frlp_transaction\x18\x01 \x01(\fR\x0erlpTransaction\x12+\n" +
	"\areceipt\x18\x02 \x01(\v2\x11.realtime.ReceiptR\areceipt\x12-\n" +
	"\binnerTxs\x18\x03 \x03(\v2\x11.realtime.InnerTxR\binnerTxs\"\x97\x02\n" +
	"\x03Log\x12\x18\n" +
	"\aaddress\x18\x01 \x01(\fR\aaddress\x12\x16\n" +
	"\x06topics\x18\x02 \x03(\fR\x06topics\x12\x12\n" +
	"\x04data\x18\x03 \x01(\fR\x04data\x12 \n" +
	"\vblockNumber\x18\x04 \x01(\x04R\vblockNumber\x12(\n" +
	"\x0ftransactionHash\x18\x05 \x01(\fR\x0ftransactionHash\x12*\n" +
	"\x10transactionIndex\x18\x06 \x01(\x04R\x10transactionIndex\x12\x1c\n" +
	"\tblockHash\x18\a \x01(\fR\tblockHash\x12\x1a\n" +
	"\blogIndex\x18\b \x01(\x04R\blogIndex\x12\x18\n" +
	"\aremoved\x18\t \x01(\bR\aremoved\"\x92\x03\n" +
	"\aReceipt\x12\x12\n" +
	"\x04type\x18\x01 \x01(\rR\x04type\x12\x12\n" +
	"\x04root\x18\x02 \x01(\fR\x04root\x12\x16\n" +
	"\x06status\x18\x03 \x01(\x04R\x06status\x12,\n" +
	"\x11cumulativeGasUsed\x18\x04 \x01(\x04R\x11cumulativeGasUsed\x12\x1c\n" +
	"\tlogsBloom\x18\x05 \x01(\fR\tlogsBloom\x12!\n" +
	"\x04logs\x18\x06 \x03(\v2\r.realtime.LogR\x04logs\x12(\n" +
	"\x0ftransactionHash\x18\a \x01(\fR\x0ftransactionHash\x12(\n" +
	"\x0fcontractAddress\x18\b \x01(\fR\x0fcontractAddress\x12\x18\n" +
	"\agasUsed\x18\t \x01(\x04R\agasUsed\x12\x1c\n" +
	"\tblockHash\x18\n" +
	" \x01(\fR\tblockHash\x12 \n" +
	"\vblockNumber\x18\v \x01(\tR\vblockNumber\x12*\n" +
	"\x10transactionIndex\x18\f \x01(\x04R\x10transactionIndex\"\xc6\x03\n" +
	"\aInnerTx\x12\x12\n" +
	"\x04dept\x18\x01 \x01(\tR\x04dept\x12%\n" +
	"\x0einternal_index\x18\x02 \x01(\tR\rinternalIndex\x12\x1b\n" +
	"\tcall_type\x18\x03 \x01(\tR\bcallType\x12\x12\n" +
	"\x04name\x18\x04 \x01(\tR\x04name\x12#\n" +
	"\rtrace_address\x18\x05 \x01(\tR\ftraceAddress\x12!\n" +
	"\fcode_address\x18\x06 \x01(\tR\vcodeAddress\x12\x12\n" +
	"\x04from\x18\a \x01(\tR\x04from\x12\x0e\n" +
	"\x02to\x18\b \x01(\tR\x02to\x12\x14\n" +
	"\x05input\x18\t \x01(\tR\x05input\x12\x16\n" +
	"\x06output\x18\n" +
	" \x01(\tR\x06output\x12\x19\n" +
	"\bis_error\x18\v \x01(\bR\aisError\x12\x10\n" +
	"\x03gas\x18\f \x01(\x04R\x03gas\x12\x19\n" +
	"\bgas_used\x18\r \x01(\x04R\agasUsed\x12\x14\n" +
	"\x05value\x18\x0e \x01(\tR\x05value\x12\x1b\n" +
	"\tvalue_wei\x18\x0f \x01(\tR\bvalueWei\x12$\n" +
	"\x0ecall_value_wei\x18\x10 \x01(\tR\fcallValueWei\x12\x14\n" +
	"\x05error\x18\x11 \x01(\tR\x05error\"\x15\n" +
	"\x13RealtimeLogsRequest\".\n" +
	"\x11RealtimeLogsReply\x12\x19\n" +
	"\brlp_logs\x18\x01 \x01(\fR\arlpLogs2\xbf\x01\n" +
	"\bRealtime\x12c\n" +
	"\x15OnRealtimeTransaction\x12$.realtime.RealtimeTransactionRequest\x1a\".realtime.RealtimeTransactionReply0\x01\x12N\n" +
	"\x0eOnRealtimeLogs\x12\x1d.realtime.RealtimeLogsRequest\x1a\x1b.realtime.RealtimeLogsReply0\x01B\fZ\n" +
	"./realtimeb\x06proto3"

var (
	file_realtime_proto_rawDescOnce sync.Once
	file_realtime_proto_rawDescData []byte
)

func file_realtime_proto_rawDescGZIP() []byte {
	file_realtime_proto_rawDescOnce.Do(func() {
		file_realtime_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_realtime_proto_rawDesc), len(file_realtime_proto_rawDesc)))
	})
	return file_realtime_proto_rawDescData
}

var file_realtime_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_realtime_proto_goTypes = []any{
	(*RealtimeTransactionRequest)(nil), // 0: realtime.RealtimeTransactionRequest
	(*RealtimeTransactionReply)(nil),   // 1: realtime.RealtimeTransactionReply
	(*Log)(nil),                        // 2: realtime.Log
	(*Receipt)(nil),                    // 3: realtime.Receipt
	(*InnerTx)(nil),                    // 4: realtime.InnerTx
	(*RealtimeLogsRequest)(nil),        // 5: realtime.RealtimeLogsRequest
	(*RealtimeLogsReply)(nil),          // 6: realtime.RealtimeLogsReply
}
var file_realtime_proto_depIdxs = []int32{
	3, // 0: realtime.RealtimeTransactionReply.receipt:type_name -> realtime.Receipt
	4, // 1: realtime.RealtimeTransactionReply.innerTxs:type_name -> realtime.InnerTx
	2, // 2: realtime.Receipt.logs:type_name -> realtime.Log
	0, // 3: realtime.Realtime.OnRealtimeTransaction:input_type -> realtime.RealtimeTransactionRequest
	5, // 4: realtime.Realtime.OnRealtimeLogs:input_type -> realtime.RealtimeLogsRequest
	1, // 5: realtime.Realtime.OnRealtimeTransaction:output_type -> realtime.RealtimeTransactionReply
	6, // 6: realtime.Realtime.OnRealtimeLogs:output_type -> realtime.RealtimeLogsReply
	5, // [5:7] is the sub-list for method output_type
	3, // [3:5] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_realtime_proto_init() }
func file_realtime_proto_init() {
	if File_realtime_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_realtime_proto_rawDesc), len(file_realtime_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_realtime_proto_goTypes,
		DependencyIndexes: file_realtime_proto_depIdxs,
		MessageInfos:      file_realtime_proto_msgTypes,
	}.Build()
	File_realtime_proto = out.File
	file_realtime_proto_goTypes = nil
	file_realtime_proto_depIdxs = nil
}
